CREATE DATABASE drivengram;

CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	description TEXT NOT NULL,
	"imageUrl" TEXT NOT NULL,
	"userId" INTEGER NOT NULL REFERENCES "users"("id"),
	"datePosted" TIMESTAMP NOT NULL DEFAULT NOW(),
	active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	cpf TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);